name: Analyze module

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish images"]
    types: [completed]

jobs:
  module:
    name: Gather module info
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == '' }}
    uses: NethServer/ns8-github-actions/.github/workflows/module-info.yml@trivy
  trivy_scan:
    name: Scan images with Trivy
    needs: module
    if: ${{ needs.module.outputs.release == 'stable' || needs.module.outputs.release == 'latest' || github.event_name == 'workflow_dispatch' }}
    uses: NethServer/ns8-github-actions/.github/workflows/scan-with-trivy.yml@trivy
    with:
      images: ${{ needs.module.outputs.images }}
      severity: "HIGH,CRITICAL"
