name: "Label PR from Weblate"

on:
  pull_request:
    types: [opened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from Weblate
        id: check_weblate
        run: |
          if [[ "${{ github.event.pull_request.user.login }}" == "weblate" ]]; then
            echo "from_weblate=true" >> $GITHUB_ENV
          else
            echo "from_weblate=false" >> $GITHUB_ENV
          fi

      - name: Assign label
        if: env.from_weblate == 'true'
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'translation'
